```html
<!-- 
    REFERRAL SOURCE TRACKER ADDITION: 
    "Referral Intelligence & Performance Analytics" 
    Add this section below the "Main Board" (<main>) and above the "Sidebar Tools" (<section>) in the base component.
-->

<section class="max-w-[1600px] mx-auto px-6 mb-12">
    <div class="flex items-center justify-between mb-6">
        <div>
            <h2 class="text-2xl font-bold text-white">Referral Intelligence</h2>
            <p class="text-slate-400 text-sm">Visualizing network density and conversion performance across industries.</p>
        </div>
        <div class="flex gap-2">
            <button class="px-4 py-2 bg-slate-800 text-slate-300 rounded-lg text-xs font-bold hover:bg-slate-700 transition">24H</button>
            <button class="px-4 py-2 bg-slate-800 text-slate-300 rounded-lg text-xs font-bold hover:bg-slate-700 transition">7D</button>
            <button class="px-4 py-2 bg-[#d4af37] text-slate-900 rounded-lg text-xs font-bold transition">30D</button>
        </div>
    </div>

    <!-- Analytics Dashboard Grid -->
    <div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        <!-- Heatmap: Category vs. Pipeline Stage -->
        <div class="lg:col-span-2 bg-[#0f172a] border border-slate-800 rounded-2xl p-6 overflow-hidden relative">
            <div class="flex justify-between items-start mb-8">
                <div>
                    <h3 class="text-white font-bold text-lg">Network Density Heatmap</h3>
                    <p class="text-slate-500 text-xs uppercase tracking-widest font-semibold mt-1">Industry Distribution x Stage</p>
                </div>
                <div class="flex items-center gap-4">
                    <div class="flex items-center gap-1.5">
                        <span class="w-3 h-3 bg-slate-800 rounded-sm"></span>
                        <span class="text-[10px] text-slate-400 font-bold uppercase">Low</span>
                    </div>
                    <div class="flex items-center gap-1.5">
                        <span class="w-3 h-3 bg-[#d4af37] rounded-sm opacity-60"></span>
                        <span class="text-[10px] text-slate-400 font-bold uppercase">Med</span>
                    </div>
                    <div class="flex items-center gap-1.5">
                        <span class="w-3 h-3 bg-[#d4af37] rounded-sm"></span>
                        <span class="text-[10px] text-slate-400 font-bold uppercase">High</span>
                    </div>
                </div>
            </div>

            <div class="overflow-x-auto">
                <table class="w-full text-left border-separate border-spacing-1">
                    <thead>
                        <tr>
                            <th class="p-2 text-[10px] text-slate-500 uppercase font-black">Category</th>
                            <th class="p-2 text-[10px] text-slate-500 uppercase font-black text-center">Identified</th>
                            <th class="p-2 text-[10px] text-slate-500 uppercase font-black text-center">Engaged</th>
                            <th class="p-2 text-[10px] text-slate-500 uppercase font-black text-center">Active</th>
                            <th class="p-2 text-[10px] text-slate-500 uppercase font-black text-center">ROI+</th>
                        </tr>
                    </thead>
                    <tbody id="heatmap-body">
                        <!-- Generated by JS -->
                    </tbody>
                </table>
            </div>
        </div>

        <!-- Metric Sidecards -->
        <div class="space-y-6">
            <!-- Quality Index Card -->
            <div class="bg-gradient-to-br from-slate-900 to-slate-800 border border-slate-700 rounded-2xl p-6 relative overflow-hidden group">
                <div class="absolute -right-4 -top-4 w-24 h-24 bg-[#d4af37] opacity-5 rounded-full blur-2xl group-hover:opacity-10 transition-opacity"></div>
                <h4 class="text-slate-400 text-xs font-bold uppercase tracking-wider mb-1">Network Quality Index</h4>
                <div class="flex items-end gap-3">
                    <span class="text-4xl font-black text-white" id="avg-quality-metric">0</span>
                    <span class="text-emerald-400 text-xs font-bold mb-1.5 flex items-center">
                        <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3" class="mr-0.5"><polyline points="18 15 12 9 6 15"></polyline></svg>
                        12%
                    </span>
                </div>
                <div class="mt-4 w-full bg-slate-700 h-1.5 rounded-full overflow-hidden">
                    <div id="quality-progress-bar" class="bg-[#d4af37] h-full transition-all duration-1000" style="width: 0%"></div>
                </div>
                <p class="mt-3 text-slate-500 text-[10px] leading-tight">Calculated based on partner responsiveness and historical deal flow conversion rates.</p>
            </div>

            <!-- Top Performing Category -->
            <div class="bg-white border border-slate-200 rounded-2xl p-6 shadow-sm">
                <h4 class="text-slate-500 text-xs font-bold uppercase tracking-wider mb-4">Top Lead Engine</h4>
                <div class="flex items-center gap-4">
                    <div class="w-12 h-12 rounded-xl bg-amber-50 flex items-center justify-center text-[#d4af37]">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M22 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>
                    </div>
                    <div>
                        <p class="text-slate-900 font-bold text-lg leading-none" id="top-cat-name">CPA/Accountants</p>
                        <p class="text-slate-500 text-xs mt-1">Contributes 42% of total volume</p>
                    </div>
                </div>
                <button class="w-full mt-6 py-2 border border-slate-200 rounded-lg text-xs font-bold text-slate-600 hover:bg-slate-50 transition">View Industry Report</button>
            </div>
        </div>
    </div>
</section>

<script>
    /**
     * Logic for the Referral Intelligence Addition
     * Append these functions or update the existing scripts.
     */

    function updateIntelligenceUI() {
        const categories = ["CPA/Accountant", "Bookkeeper", "Business Broker", "Real Estate Agent", "Equipment Dealer", "Bank Manager"];
        const heatmapBody = document.getElementById('heatmap-body');
        
        if (!heatmapBody) return;
        heatmapBody.innerHTML = '';

        // Calculate Category vs Stage Density
        categories.forEach(cat => {
            const row = document.createElement('tr');
            
            // Helper to count by stage grouping
            const getCount = (stageKeywords) => {
                return sources.filter(s => s.category === cat && stageKeywords.some(k => s.stage.includes(k))).length;
            };

            const counts = {
                identified: getCount(['Identified']),
                engaged: getCount(['Contacted', 'Conversation']),
                active: getCount(['Agreement', 'Active']),
                dormant: getCount(['Dormant'])
            };

            const getHeatColor = (count) => {
                if (count === 0) return 'bg-slate-800/50 text-slate-600';
                if (count < 3) return 'bg-[#d4af37]/20 text-[#d4af37]';
                if (count < 6) return 'bg-[#d4af37]/50 text-white';
                return 'bg-[#d4af37] text-navy-deep font-bold';
            };

            row.innerHTML = `
                <td class="p-2 text-xs font-bold text-slate-300 border-b border-slate-800/50">${cat}</td>
                <td class="p-2 text-center border-b border-slate-800/50"><div class="rounded py-2 text-[10px] ${getHeatColor(counts.identified)}">${counts.identified}</div></td>
                <td class="p-2 text-center border-b border-slate-800/50"><div class="rounded py-2 text-[10px] ${getHeatColor(counts.engaged)}">${counts.engaged}</div></td>
                <td class="p-2 text-center border-b border-slate-800/50"><div class="rounded py-2 text-[10px] ${getHeatColor(counts.active)}">${counts.active}</div></td>
                <td class="p-2 text-center border-b border-slate-800/50"><div class="rounded py-2 text-[10px] ${getHeatColor(counts.dormant)}">${counts.dormant}</div></td>
            `;
            heatmapBody.appendChild(row);
        });

        // Update Average Quality Metric
        const avgQuality = sources.length > 0 
            ? Math.round(sources.reduce((acc, curr) => acc + (curr.qualityScore || 0), 0) / sources.length) 
            : 0;
        
        const metricEl = document.getElementById('avg-quality-metric');
        const progressEl = document.getElementById('quality-progress-bar');
        
        if(metricEl) metricEl.innerText = avgQuality + '%';
        if(progressEl) setTimeout(() => progressEl.style.width = avgQuality + '%', 500);

        // Find Top Category
        const catCounts = {};
        sources.forEach(s => catCounts[s.category] = (catCounts[s.category] || 0) + 1);
        const topCat = Object.keys(catCounts).reduce((a, b) => catCounts[a] > catCounts[b] ? a : b, 'None');
        
        const topCatEl = document.getElementById('top-cat-name');
        if(topCatEl) topCatEl.innerText = topCat;
    }

    // Intercept original renderBoard to also update intelligence
    const originalRenderBoard = renderBoard;
    renderBoard = function() {
        originalRenderBoard();
        updateIntelligenceUI();
    };

    // Initialize on load
    window.addEventListener('DOMContentLoaded', updateIntelligenceUI);
</script>

<style>
    /* Addition-specific styles */
    #heatmap-body tr:hover td {
        background: rgba(255,255,255,0.02);
    }
    
    @keyframes pulse-gold {
        0% { box-shadow: 0 0 0 0 rgba(212, 175, 55, 0.4); }
        70% { box-shadow: 0 0 0 10px rgba(212, 175, 55, 0); }
        100% { box-shadow: 0 0 0 0 rgba(212, 175, 55, 0); }
    }

    .quality-glow {
        animation: pulse-gold 2s infinite;
    }
</style>
```