(function() {
    /**
     * js/ui-sliders.js
     * Growth & Scaling Simulator Extension
     * Swiss Ledger Design System
     */

    const createScalingSimulator = () => {
        const mainGrid = document.querySelector('.main-grid');
        if (!mainGrid) return;

        // Create the simulator container
        const simulatorContainer = document.createElement('section');
        simulatorContainer.className = 'input-section';
        simulatorContainer.style.gridColumn = '1 / -1';
        simulatorContainer.style.borderTop = '2px solid var(--border)';
        simulatorContainer.style.borderRight = 'none';
        simulatorContainer.style.backgroundColor = 'rgba(255, 255, 255, 0.2)';

        simulatorContainer.innerHTML = `
            <div class="badge">SIMULATOR REV. 1.0</div>
            <h2 style="font-size: 24px; font-weight: 800; margin-bottom: 30px; text-transform: uppercase; letter-spacing: -0.02em;">
                Growth & Scaling Simulator
            </h2>
            
            <div style="display: grid; grid-template-columns: 1fr 1.2fr; gap: 40px;">
                <div class="simulation-controls">
                    <div class="form-group">
                        <label>Scaling Multiplier: <span id="scaleLabel" style="color: var(--accent)">2x</span></label>
                        <input type="range" id="scaleSlider" min="1" max="10" step="0.5" value="2" 
                               style="padding: 0; height: 4px; cursor: pointer; -webkit-appearance: none; background: var(--ink);">
                    </div>
                    <div class="form-group">
                        <label>Diminishing Returns Rate (%)</label>
                        <input type="number" id="diminishingReturns" value="5" step="1" max="50">
                        <p style="font-family: 'JetBrains Mono', monospace; font-size: 10px; color: #666; margin-top: 5px;">
                            Est. increase in CAC for every 2x scale.
                        </p>
                    </div>
                </div>

                <div class="simulation-results" style="border: 1px solid var(--border); padding: 25px; background: white;">
                    <label style="margin-bottom: 20px;">12-Month Projection Summary</label>
                    <div id="projectionGrid" style="display: grid; grid-template-columns: 1fr 1fr; gap: 20px;">
                        <div>
                            <div style="font-family: 'JetBrains Mono', monospace; font-size: 9px; color: #666;">NEW MONTHLY SPEND</div>
                            <div id="projNewSpend" style="font-size: 18px; font-weight: 700;">$0</div>
                        </div>
                        <div>
                            <div style="font-family: 'JetBrains Mono', monospace; font-size: 9px; color: #666;">CUMULATIVE CASH GAP</div>
                            <div id="projCashGap" style="font-size: 18px; font-weight: 700; color: var(--danger);">$0</div>
                        </div>
                        <div>
                            <div style="font-family: 'JetBrains Mono', monospace; font-size: 9px; color: #666;">PROJECTED ANNUAL REV</div>
                            <div id="projAnnualRev" style="font-size: 18px; font-weight: 700; color: var(--success);">$0</div>
                        </div>
                        <div>
                            <div style="font-family: 'JetBrains Mono', monospace; font-size: 9px; color: #666;">BREAK-EVEN MONTH</div>
                            <div id="projBreakeven" style="font-size: 18px; font-weight: 700;">--</div>
                        </div>
                    </div>
                    <div style="margin-top: 25px; height: 60px; display: flex; align-items: flex-end; gap: 2px;" id="visualChart">
                        <!-- Bars generated by JS -->
                    </div>
                </div>
            </div>
        `;

        mainGrid.appendChild(simulatorContainer);
        initSimulationLogic();
    };

    const initSimulationLogic = () => {
        const scaleSlider = document.getElementById('scaleSlider');
        const diminishingInput = document.getElementById('diminishingReturns');
        const scaleLabel = document.getElementById('scaleLabel');
        
        const updateSimulation = () => {
            // Pull base metrics from the main app
            const baseSpend = parseFloat(document.getElementById('spend').value) || 0;
            const baseCustomers = parseFloat(document.getElementById('customers').value) || 0;
            const arpu = parseFloat(document.getElementById('arpu').value) || 0;
            const margin = (parseFloat(document.getElementById('margin').value) / 100) || 0;
            
            const multiplier = parseFloat(scaleSlider.value);
            const decayRate = (parseFloat(diminishingInput.value) / 100) || 0;
            
            scaleLabel.innerText = `${multiplier}x`;

            const targetMonthlySpend = baseSpend * multiplier;
            const incrementalSpend = targetMonthlySpend - baseSpend;
            
            // Scaled CAC with diminishing returns (simplified power law)
            const scaledCac = (baseSpend / baseCustomers) * Math.pow(multiplier, decayRate);
            const scaledNewCustomers = targetMonthlySpend / scaledCac;
            const monthlyIncrementalGP = scaledNewCustomers * arpu * margin;

            let cumulativeGap = 0;
            let maxGap = 0;
            let breakevenMonth = -1;
            let monthData = [];

            // 12-month projection
            // We assume the incremental spend starts Month 1
            // We track the cash flow gap (Incremental Spend - Incremental Gross Profit)
            for (let m = 1; m <= 12; m++) {
                // Simplified: Cumulative Revenue builds up as cohorts stack
                const monthlyCohortsGP = (monthlyIncrementalGP * m); 
                const monthlySpendTotal = incrementalSpend * m;
                const netCashflow = monthlyCohortsGP - monthlySpendTotal;
                
                if (netCashflow < 0 && Math.abs(netCashflow) > maxGap) {
                    maxGap = Math.abs(netCashflow);
                }

                if (breakevenMonth === -1 && netCashflow > 0) {
                    breakevenMonth = m;
                }
                
                monthData.push(netCashflow);
            }

            // Update UI
            document.getElementById('projNewSpend').innerText = `$${targetMonthlySpend.toLocaleString(undefined, {maximumFractionDigits: 0})}`;
            document.getElementById('projCashGap').innerText = `$${maxGap.toLocaleString(undefined, {maximumFractionDigits: 0})}`;
            document.getElementById('projAnnualRev').innerText = `$${(monthlyIncrementalGP * 12).toLocaleString(undefined, {maximumFractionDigits: 0})}`;
            document.getElementById('projBreakeven').innerText = breakevenMonth === -1 ? '12+ Mo.' : `${breakevenMonth} Mo.`;

            // Update Chart
            const chart = document.getElementById('visualChart');
            chart.innerHTML = '';
            const maxVal = Math.max(...monthData.map(Math.abs), 1);
            
            monthData.forEach(val => {
                const bar = document.createElement('div');
                const height = (Math.abs(val) / maxVal) * 100;
                bar.style.flex = '1';
                bar.style.height = `${Math.max(height, 5)}%`;
                bar.style.backgroundColor = val < 0 ? 'var(--danger)' : 'var(--success)';
                bar.style.opacity = '0.8';
                chart.appendChild(bar);
            });
        };

        // Attach listeners to both simulation and base inputs
        [scaleSlider, diminishingInput].forEach(el => el.addEventListener('input', updateSimulation));
        ['spend', 'customers', 'arpu', 'margin'].forEach(id => {
            document.getElementById(id).addEventListener('input', updateSimulation);
        });

        // Initial Run
        updateSimulation();
    };

    // Initialize when DOM is ready
    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', createScalingSimulator);
    } else {
        createScalingSimulator();
    }
})();