import React from 'react';

const InvestorMemoPreview: React.FC = () => {
  return (
    <div style={{
      backgroundColor: 'var(--bg-deep)',
      color: 'var(--text-main)',
      fontFamily: "'Inter', sans-serif",
      padding: '2rem',
      minHeight: '100vh'
    }}>
      <style>{`
        .memo-container {
          max-width: 1100px;
          margin: 0 auto;
          display: grid;
          grid-template-columns: 1fr 320px;
          gap: 24px;
        }
        .memo-paper {
          background: #ffffff;
          color: #1a1a1a;
          padding: 60px;
          border-radius: 4px;
          box-shadow: 0 20px 50px rgba(0,0,0,0.3);
          font-family: 'Inter', serif;
        }
        .memo-header {
          border-bottom: 2px solid #000;
          padding-bottom: 20px;
          margin-bottom: 40px;
          display: flex;
          justify-content: space-between;
          align-items: flex-end;
        }
        .memo-title {
          font-weight: 800;
          font-size: 1.5rem;
          text-transform: uppercase;
          letter-spacing: -0.02em;
        }
        .confidential-tag {
          font-family: 'JetBrains Mono', monospace;
          font-size: 0.7rem;
          background: #000;
          color: #fff;
          padding: 4px 8px;
        }
        .memo-section { margin-bottom: 32px; }
        .memo-section h3 {
          font-size: 0.85rem;
          text-transform: uppercase;
          letter-spacing: 0.1em;
          color: #666;
          margin-bottom: 12px;
          border-bottom: 1px solid #eee;
          padding-bottom: 4px;
        }
        .memo-section p {
          font-size: 1rem;
          line-height: 1.6;
          color: #333;
        }
        .sidebar-card {
          background: var(--bg-card);
          border: 1px solid var(--border);
          padding: 24px;
          border-radius: 8px;
          margin-bottom: 20px;
        }
        .readiness-gauge {
          text-align: center;
          padding: 20px 0;
        }
        .score-value {
          font-size: 3rem;
          font-weight: 800;
          color: var(--primary);
          line-height: 1;
        }
        .audit-item {
          display: flex;
          align-items: center;
          gap: 12px;
          margin-bottom: 12px;
          font-size: 0.85rem;
        }
        .status-dot {
          width: 8px;
          height: 8px;
          border-radius: 50%;
        }
        .status-success { background: var(--primary); box-shadow: 0 0 10px var(--primary); }
        .status-warning { background: var(--secondary); }
        .data-room-list {
          list-style: none;
          margin-top: 16px;
        }
        .data-room-item {
          padding: 8px;
          border: 1px solid var(--border);
          border-radius: 4px;
          margin-bottom: 8px;
          font-size: 0.75rem;
          display: flex;
          justify-content: space-between;
          background: var(--bg-surface);
        }
        .btn-full {
          width: 100%;
          padding: 12px;
          border-radius: 4px;
          font-weight: 700;
          cursor: pointer;
          border: none;
          margin-top: 8px;
        }
        .mono { font-family: 'JetBrains Mono', monospace; }
      `}</style>

      <div className="memo-container">
        {/* Document Preview */}
        <div className="memo-paper">
          <div className="memo-header">
            <div>
              <div className="memo-title">Investment Memo: Project Alpha</div>
              <div style={{ fontSize: '0.85rem', color: '#666' }}>Generated by CFO-in-a-Box AI • October 2023</div>
            </div>
            <div className="confidential-tag">STRICTLY CONFIDENTIAL</div>
          </div>

          <div className="memo-section">
            <h3>Executive Summary</h3>
            <p>
              The company has demonstrated consistent MoM growth of 14% with a capital-efficient 
              acquisition model. Current burn is optimized at $42k/mo with a remaining runway 
              of 18 months. This round is positioned to scale the automated sales infrastructure 
              validated in Q3.
            </p>
          </div>

          <div className="memo-section">
            <h3>Financial Snapshot</h3>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '20px', margin: '20px 0' }}>
              <div style={{ borderLeft: '3px solid #000', paddingLeft: '12px' }}>
                <div style={{ fontSize: '0.7rem', color: '#888' }}>ANNUAL RUN RATE</div>
                <div style={{ fontWeight: '700' }}>$1.2M</div>
              </div>
              <div style={{ borderLeft: '3px solid #000', paddingLeft: '12px' }}>
                <div style={{ fontSize: '0.7rem', color: '#888' }}>GROSS MARGIN</div>
                <div style={{ fontWeight: '700' }}>82%</div>
              </div>
              <div style={{ borderLeft: '3px solid #000', paddingLeft: '12px' }}>
                <div style={{ fontSize: '0.7rem', color: '#888' }}>CAC/LTV</div>
                <div style={{ fontWeight: '700' }}>4.2x</div>
              </div>
            </div>
          </div>

          <div className="memo-section">
            <h3>The Opportunity</h3>
            <p>
              Unlike competitors relying on heavy manual sales cycles, our AI-driven lead 
              qualification engine has reduced the sales cycle from 45 days to 12. We are 
              seeking $2M in Seed+ funding to expand into the enterprise tier where 
              pre-contract interest exceeds $400k in LOIs.
            </p>
          </div>

          <div className="memo-section">
            <h3>Risk Assessment</h3>
            <p>
              Primary risks include platform dependency on Stripe/AWS stack and 
              potential compression of margins as we scale the outbound team. 
              Mitigation strategies are outlined in the full Data Room.
            </p>
          </div>
        </div>

        {/* Sidebar Tools */}
        <div className="sidebar">
          <div className="sidebar-card">
            <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', fontWeight: 600, textTransform: 'uppercase' }}>Funding Readiness</div>
            <div className="readiness-gauge">
              <div className="score-value">84</div>
              <div style={{ fontSize: '0.8rem', color: 'var(--primary)', marginTop: '4px', fontWeight: 700 }}>INVESTOR READY</div>
            </div>
            <div className="audit-list">
              <div className="audit-item">
                <div className="status-dot status-success"></div>
                <span className="mono">Clean P&L (LTM)</span>
              </div>
              <div className="audit-item">
                <div className="status-dot status-success"></div>
                <span className="mono">Verified Cap Table</span>
              </div>
              <div className="audit-item">
                <div className="status-dot status-warning"></div>
                <span className="mono">Tax Docs (Pending)</span>
              </div>
            </div>
          </div>

          <div className="sidebar-card">
            <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', fontWeight: 600, textTransform: 'uppercase' }}>AI Data Room</div>
            <div className="data-room-list">
              <div className="data-room-item">
                <span>📁 01_Financials</span>
                <span style={{ color: var(--primary) }}>READY</span>
              </div>
              <div className="data-room-item">
                <span>📁 02_Legal_Docs</span>
                <span style={{ color: var(--primary) }}>READY</span>
              </div>
              <div className="data-room-item">
                <span>📁 03_IP_Patents</span>
                <span style={{ color: 'var(--text-muted)' }}>EMPTY</span>
              </div>
            </div>
            <button className="btn-full" style={{ background: 'var(--primary)', color: '#000' }}>Generate Access Link</button>
          </div>

          <div className="sidebar-card" style={{ background: 'transparent' }}>
            <button className="btn-full" style={{ background: 'transparent', border: '1px solid var(--border)', color: '#fff' }}>Export PDF Memo</button>
            <button className="btn-full" style={{ background: 'transparent', border: '1px solid var(--border)', color: '#fff' }}>Update AI Narrative</button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default InvestorMemoPreview;